---
- name: Install netdata
  ansible.builtin.package:
    name: netdata
    state: latest

- name: Copy netdata config from template
  template: 
    src: netdata.conf.j2
    dest: /etc/netdata/netdata.conf
  notify: restart netdata
