---
# Disables firewalld service. If no such service - stay silent and do nothing
- name: disable firewalld
  service:
       name: firewalld
       state: stopped
       enabled: False
  ignore_errors: yes
  when:  ansible_facts['os_family'] == 'CentOS'
  
- name: disable selinux
  ansible.posix.selinux:
    state: disabled
  notify: reboot selinux
  when:  ansible_facts['os_family'] == 'CentOS'

# Fix for local static addresses. It`s better to do it in DNS.
# non needed if all hosts from invenory regisered in DNS
- name: add all backend servers from inventory to /etc/hosts
  become: true
  blockinfile:
    path: /etc/hosts
    block: |
      {% for host in groups['backend'] %}
      {{ hostvars[host].ansible_host }} {{ host }}
      {% endfor %}

# Start systemd-resolved to allow nginx proxy_pass directive use hosts file
# not needed if all hosts from inventory registered in DNS (same as previous)
- name: enable systemd-resolved 
  service:
       name: systemd-resolved
       state: started
       enabled: True


